name: Publish
on:
  push:
    # tags:
    #   - '*'
    branches:
      - github_release

permissions:
  contents: write

env:
  version: v0.0.2-alpha.1

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - linux
          - darwin
          - windows
        arch:
          - amd64
          - arm64

    steps:
      - uses: actions/checkout@v4
      - run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o main-${{matrix.os}}-${{matrix.arch}}-${{env.version}}
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main-${{matrix.os}}-${{matrix.arch}}-${{env.version}}
          # tag: ${{ github.ref }}
          tag: ${{env.version}}
          overwrite: true